name: carnd
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - matplotlib
    - jupyter
    - opencv
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.5
    - pyqt=5
    - pip:
        - moviepy
        - tensorflow==2.0.0-beta1
        - keras==2.3.0